<a href="https://colab.research.google.com/github/Ponmathi-bit/my_project/blob/main/numpySelfLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#Creating arrays
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
range_array = np.arange(0, 10, 2)
random_array = np.random.rand(3, 3)

In [5]:
print(a)
print(b)
print(c)
print(zeros)
print(ones)
print(range_array)
print(random_array)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[[0.40478249 0.4899652  0.34132972]
 [0.26300624 0.69301411 0.2717416 ]
 [0.11244326 0.12614874 0.40008939]]


In [8]:
#Array Indexing and Slicing
print(a[0])
print(b[1,1])
slice_a = a[1:3]
slice_b = b[:,1]
print(slice_a)
print(slice_b)

1
4
[2 3]
[2 4]


In [9]:
#Element-wise Operator
x = np.array([1,2,3])
y = np.array([4,5,6])

z = x + y
print(z)

z = x*y
print(z)

z = x + 10
print(z)

[5 7 9]
[ 4 10 18]
[11 12 13]


In [12]:
#Linear Algebra

# 2x + y = 1
# x - y = -1

p = np.array([[2,1],[1,-1]])
v = np.array([1,-1])

m = np.linalg.solve(p,v)
print(m)

n = np.dot(p, v)
print(n)


[0. 1.]
[1 2]


In [15]:
print(a.T)
print(np.linalg.inv(b))

[1 2 3 4]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
#Aggregations and Statistical Operations
print(np.sum(b))
print(np.mean(b))
print(np.std(b))
print(np.min(b))
print(np.max(b))


10
2.5
1.118033988749895
1
4


In [18]:
#Random numbers
print(np.random.rand())
print(np.random.randint(0,100))
print(np.random.randn(5))
print(np.random.seed)

0.24179320884314992
82
[ 0.60764478  2.07169372 -1.14170129 -0.31839323 -0.59227585]
<built-in function seed>
